# Generated by Django 2.1.5 on 2020-06-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='orderNum',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='workorder',
            name='orderNum',
            field=models.CharField(default='', max_length=64),
        ),
    ]
